name: Frontend Login Tests CI

on:
  push:
    branches: ["main", "feat/setup-test"]
  pull_request:
    branches: ["main", "feat/setup-test"]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: mvn -q dependency:resolve

      - name: Start Backend Server
        working-directory: ./backend
        run: |
          mvn spring-boot:run &
          sleep 10

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

       # 1) Validation Test (frontend)
      - name: Run Login Validation Tests
        working-directory: ./frontend
        run: npm run test:validationFrontend

      # 2) Integration Test
      - name: Run Login Integration Tests
        working-directory: ./frontend
        run: npm run test:loginIntegrationFrontend

      # 3) Mock Test
      - name: Run Login Mock Tests
        working-directory: ./frontend
        run: npm run test:loginMockFrontend

      - name: Start Frontend Server
        working-directory: ./frontend
        run: |
          npm start &
          sleep 10
            
      # 4) E2E (Cypress)
      - name: Install Cypress
        working-directory: ./frontend
        run: npx cypress install

      - name: Run Login E2E Tests
        working-directory: ./frontend
        run: npm run test:e2eFrontend

      # Upload ALL coverage results
      - name: Generate coverage report
        working-directory: ./frontend
        run: npm run test:coverage
        
      - name: Upload Login Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: login-coverage
          path: frontend/coverage
